'use strict';

const vscode = require('vscode');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { assertSafeLocalPath } = require('../helpers/localFiles');
const { readBootstrapProject } = require('./bootstrap');

const TASK_TIMEOUT_MS = 15 * 60 * 1000;
const END_EVENT_GRACE_MS = 250;

/** Accept only the setup commands we generate; credentials never belong in argv. */
function validateArguments(args) {
    if (!Array.isArray(args) || args.some(value => typeof value !== 'string')) throw new Error('Invalid SuiteCloud setup command.');
    const fixed = [
        ['--version'],
        ['account:setup', '--interactive'],
        ['project:validate'],
        ['project:deploy', '--dryrun'],
        ['project:deploy']
    ];
    if (fixed.some(command => command.length === args.length && command.every((value, index) => value === args[index]))) return;
    if (args.length === 3 && args[0] === 'account:setup:ci' && args[1] === '--select' && /^[A-Za-z0-9][A-Za-z0-9_.-]{0,79}$/.test(args[2])) return;
    throw new Error('Unsupported SuiteCloud setup command. Use the SuperSuite initialization wizard.');
}

class SuiteCloudTaskRunner {
    constructor(output) {
        this.output = output;
        this.owned = new Set();
        this.activeRoots = new Set();
        this.disposed = false;
    }

    dispose() {
        this.disposed = true;
        for (const operation of [...this.owned]) operation.cancel();
    }

    /**
     * Run the installed Oracle CLI in a visible VS Code task. Authentication stays
     * in the CLI's browser/terminal flow; no token, password, or certificate is
     * interpolated into a shell command or written to SuperSuite's output channel.
     * The generated project is checked before each command, including CLI config
     * scripts, so a changed deployment cannot run through the setup workflow.
     */
    async run(folder, projectRoot, args, title = 'SuperSuite: SuiteCloud setup') {
        if (this.disposed) return { cancelled: true };
        if (!vscode.workspace.isTrusted) throw new Error('Trust this workspace before running SuiteCloud setup.');
        if (folder?.uri?.scheme !== 'file' || typeof projectRoot !== 'string' || !path.isAbsolute(projectRoot)) throw new Error('SuiteCloud setup requires a filesystem workspace and an absolute project folder.');
        validateArguments(args);
        const root = path.resolve(projectRoot);
        const key = process.platform === 'win32' ? root.toLowerCase() : root;
        if (this.activeRoots.has(key)) throw new Error('A SuiteCloud setup task is already running for this project.');
        this.activeRoots.add(key);
        try {
            await assertSafeLocalPath(folder.uri.fsPath, root);
            const generated = await readBootstrapProject(folder.uri.fsPath);
            const generatedRoot = generated && path.resolve(generated.projectRoot);
            if (!generatedRoot || (process.platform === 'win32' ? generatedRoot.toLowerCase() : generatedRoot) !== key) throw new Error('SuiteCloud tasks require the unchanged project generated by SuperSuite Init. Run Init again to prepare or verify that project.');
            if (!(await fs.stat(root)).isDirectory()) throw new Error('SuiteCloud setup project must be a directory.');
            if (this.disposed) return { cancelled: true };
            const shell = new vscode.ShellExecution('suitecloud', args.map(value => ({ value, quoting: vscode.ShellQuoting.Strong })), { cwd: root });
            const task = new vscode.Task({ type: 'supersuite-setup', supersuiteSetupId: crypto.randomUUID() }, folder, title, 'SuperSuite', shell, []);
            task.presentationOptions = {
                reveal: vscode.TaskRevealKind.Always,
                focus: args.includes('--interactive'),
                panel: vscode.TaskPanelKind.Dedicated,
                showReuseMessage: false,
                clear: false
            };
            task.runOptions = { reevaluateOnRerun: false };
            return await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title, cancellable: true }, (_progress, token) => this.execute(task, token));
        } finally { this.activeRoots.delete(key); }
    }

    execute(task, token) {
        if (this.disposed || token.isCancellationRequested) return Promise.resolve({ cancelled: true });
        return new Promise((resolve, reject) => {
            let finished = false;
            let timeout;
            let endFallback;
            const subscriptions = [];
            const operation = { execution: undefined, cancelled: false, terminated: false };
            const cleanup = () => {
                clearTimeout(timeout);
                clearTimeout(endFallback);
                subscriptions.forEach(subscription => subscription.dispose());
                this.owned.delete(operation);
            };
            const finish = (result, error) => {
                if (finished) return;
                finished = true;
                cleanup();
                if (error) reject(error);
                else resolve(result);
            };
            const terminate = () => {
                if (!operation.execution || operation.terminated) return;
                operation.terminated = true;
                try { operation.execution.terminate(); } catch {
                    this.output.appendLine('SuperSuite could not stop its SuiteCloud task. Close that task terminal if it is still running.');
                }
            };
            operation.cancel = error => {
                operation.cancelled = true;
                // Detach completion listeners first: terminate may immediately
                // emit an end event, which must not swallow a timeout error.
                finish({ cancelled: true }, error);
                terminate();
            };
            const matches = event => (operation.execution && event.execution === operation.execution) || event.execution?.task?.definition?.supersuiteSetupId === task.definition.supersuiteSetupId;
            this.owned.add(operation);
            // Register before executeTask: very short processes can finish before
            // executeTask resolves. The per-run ID also excludes unrelated tasks.
            subscriptions.push(vscode.tasks.onDidEndTaskProcess(event => {
                if (!matches(event)) return;
                if (operation.cancelled || event.exitCode === undefined) return finish({ cancelled: true });
                if (event.exitCode !== 0) return finish(undefined, new Error(`SuiteCloud exited with code ${event.exitCode}. Review the SuiteCloud task terminal, correct the reported error, and run Init again to resume.`));
                finish({ cancelled: false, exitCode: 0 });
            }));
            subscriptions.push(vscode.tasks.onDidEndTask(event => {
                if (!matches(event) || finished) return;
                // Some terminated/failed-to-start tasks have no process event. A
                // brief grace period lets a nearby process event supply its code.
                clearTimeout(endFallback);
                endFallback = setTimeout(() => finish({ cancelled: true }), END_EVENT_GRACE_MS);
            }));
            subscriptions.push(token.onCancellationRequested(() => operation.cancel()));
            if (this.disposed || token.isCancellationRequested) { operation.cancel(); return; }
            timeout = setTimeout(() => operation.cancel(new Error('SuiteCloud setup timed out after 15 minutes and was stopped. Check the SuiteCloud task terminal, then run Init again to resume.')), TASK_TIMEOUT_MS);
            this.output.appendLine(`Starting SuiteCloud ${task.execution.args[0].value}. Follow any instructions in its task terminal.`);
            // Promise.resolve().then also captures a synchronous executeTask error.
            Promise.resolve().then(() => {
                if (operation.cancelled) return undefined;
                return vscode.tasks.executeTask(task);
            }).then(execution => {
                operation.execution = execution;
                // Cancellation can precede executeTask's resolution; only this
                // runner's returned execution is ever terminated.
                if (operation.cancelled) terminate();
            }, () => finish(undefined, new Error('Could not start SuiteCloud. Install the Oracle SuiteCloud CLI for Node.js and its prerequisites, make suitecloud available on PATH, and run Init again.')));
        });
    }
}

module.exports = { SuiteCloudTaskRunner, validateArguments };
